# Generated by Django 4.2.1 on 2023-07-27 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=120, null=True)),
                ('category_code', models.CharField(max_length=50, null=True, unique=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('sh_description', models.CharField(db_column='short_description', max_length=10, null=True)),
                ('lg_description', models.CharField(db_column='long_description', max_length=20, null=True)),
                ('status', models.SmallIntegerField(default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(db_column='image', null=True, upload_to='category_img/')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', default='NA', max_length=100)),
                ('cat_id', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='productmanagement.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
