# Generated by Django 4.2.1 on 2023-08-30 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0002_product_created_at_product_image_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
