# Generated by Django 4.2.1 on 2023-08-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0003_remove_product_cat_id_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_column='product_name', default='NA', max_length=100),
        ),
    ]
