# Generated by Django 4.2.1 on 2023-06-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productmanagement', '0004_alter_category_created_at_alter_category_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
