# Generated by Django 4.2.1 on 2023-05-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_category_category_code_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vendor_code',
            field=models.CharField(default='00000', max_length=50, null=True),
        ),
    ]
