# Generated by Django 4.2.1 on 2023-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0006_alter_category_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='vendor_code',
            field=models.CharField(default=4, editable=False, max_length=50),
        ),
    ]
