# Generated by Django 4.2.1 on 2023-05-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0007_alter_category_vendor_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vendor_code',
        ),
    ]
