# Generated by Django 4.2.1 on 2023-05-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0008_remove_category_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vendor_code',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
