# Generated by Django 4.2.1 on 2023-05-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0011_remove_category_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
