# Generated by Django 4.2.1 on 2023-05-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0014_alter_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
