# Generated by Django 4.2.1 on 2023-05-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0015_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
