# Generated by Django 4.2.1 on 2023-05-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectmanagement', '0016_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=120, null=True)),
                ('category_code', models.CharField(max_length=50, null=True, unique=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
