# Generated by Django 4.2.1 on 2023-05-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0018_alter_product_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(db_column='p_id', primary_key=True, serialize=False),
        ),
    ]
