# Generated by Django 4.2.1 on 2023-05-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0019_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sh_description',
            field=models.CharField(db_column='short_description', max_length=10, null=True),
        ),
    ]
